---

- name: Assert | Network facts
  ansible.builtin.setup:
    gather_subset:
      - network
  become: true
  register: nameserver_current_host_facts

- name: Assert | debug network facts
  ansible.builtin.debug:
    var: nameserver_current_host_facts.ansible_facts

- name: Assert | test if hostname_reboot is set correctly
  ansible.builtin.assert:
    that:
      - nameserver_current_host_facts.ansible_facts['ansible_' ~ (preferred_nic | replace('-', '_'))] is defined
      - nameserver_current_host_facts.ansible_facts['ansible_' ~ (preferred_nic | replace('-', '_'))].ipv4.address is defined
    quiet: yes
  when:
    - preferred_nic is defined
    - preferred_nic != ""
