---
- name: ansible-nameserver | bind_config | bind directory
  ansible.builtin.file:
    path: "{{ bind_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: ansible-nameserver | bind_config | gather all ips of the bind client group
  ansible.builtin.setup:
  loop: "{{ groups[bind_clients] | list }}"
  loop_control:
    loop_var: registeredhost
  delegate_facts: true
  delegate_to: "{{ registeredhost }}"
  register: registeredbindhosts

- name: ansible-nameserver | bind_config | debug all registered IPs
  ansible.builtin.debug:
    var: registeredbindhosts
    verbosity: 3

- name: ansible-nameserver | bind_config | configuring bind
  ansible.builtin.template:
    src: etc/bind/named.conf.options.j2
    dest: "{{ bind_conf_dir }}/named.conf.options"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - ansible-nameserver | reload bind
