---

- name: ansible-nameserver | deps | set hostname
  include_role:
    name: tcharl.ansible_hostname
  vars:
    hostname: "{{ hostname  | default(nameserver_machine_hostname.stdout) }}"
    hostname_reboot: false
    ansible_become: true

- name: ansible-nameserver | deps | set hostname
  import_role:
    name: tcharl.ansible_securehost
