---

- name: ansible-nameserver | deps | install netaddr
  ansible.builtin.package:
    name: python-netaddr
    state: present
  become: True

- name: ansible-nameserver | host | get current hostname
  command: "hostname"
  register: nameserver_machine_hostname
  changed_when: false

- name: ansible-nameserver | host | set hostname
  include_role:
    name: tcharl.ansible_hostname
  when: standalone_role
  vars:
    hostname: "{{ hostname  | default(nameserver_machine_hostname.stdout) }}"
    hostname_reboot: false
    ansible_become: true

- name: ansible-nameserver | ipa_dns_client | set hostname
  import_role:
    name: tcharl.ansible_securehost
  when: standalone_role