---
- name: ansible-nameserver | freeipa-deps | import securehost
  ansible.builtin.import_role:
    name: tcharl.ansible_securehost
  when: |
    idm_group | default("") | string in group_names or idm_client_group | default("") | string in group_names
  tags:
    - dependency
