---
- name: ansible-nameserver | host | get current hostname
  command: "hostname"
  register: machine_hostname
  changed_when: false

- name: ansible-nameserver | host | set hostname
  include_role:
    name: tcharl.ansible_hostname
  vars:
    hostname: "{{ ns_hostname  | default(machine_hostname.stdout) }}"
    hostname_reboot: false
    ansible_become: true

- name: ansible-nameserver | host_entries | host file configuration for additional entries
  include_tasks: host.yml
  vars:
    hostname: "{{ entry.name }}"
    ip: "{{ entry.ip }}"
  loop: "{{ hosts_entries | default([])}}"
  loop_control:
    loop_var: entry
