---

- name: ansible-nameserver | host | set hostname
  include_role:
    name: tcharl.ansible_hostname
  vars:
    hostname: "{{ ns_hostname }}"
    hostname_reboot: false
    ansible_become: true

- name: ansible-nameserver | host_entries | host file configuration for ipv4
  include_tasks: host.yml
  vars:
    hostname: "{{ entry.name }}"
    ip: "{{ entry.ip }}"
  loop: "{{ hosts_entries }}"
  loop_control:
    loop_var: entry
