---

- name: ansible-nameserver | install | docker
  ansible.builtin.import_role:
    name: tcharl.ansible_containerization
  tags:
    - standalone

- name: ansible-nameserver | install | python-docker
  ansible.builtin.package:
    name:
     - python-docker
    state: present
  become: true
