---

- name: ansible-nameserver | ipa_dns_client | debug dns zone creation
  ansible.builtin.debug:
    msg: "echo '{{ (current_host_ip.msg | ipsubnet(16) | ansible.netcommon.ipaddr('revdns')) | replace('0.0.','') }}' | ipa dnszone-add --name-from-ip={{ current_host_ip.msg | ipsubnet(16) }}"

- name: ansible-nameserver | ipa_dns_client | ensure reverse zone is created
  shell: >
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null &&
    ipa dnszone-add {{ (current_host_ip.msg | ipsubnet(16) | ansible.netcommon.ipaddr('revdns')) | replace('0.0.','') }}
  no_log: "{{ secure_logs }}"
  failed_when: False
  delegate_to: "{{ groups[idm_group][0] }}"
  changed_when: False
  become: true

- name: ansible-nameserver | ipa_dns_client | allow ptr sync on dns zone
  shell: >
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null &&
    ipa dnszone-mod --allow-sync-ptr=1 {{ company_domain }}
  failed_when: False
  changed_when: False
  delegate_to: "{{ groups[idm_group][0] }}"
  no_log: "{{ secure_logs }}"

- name: ansible-nameserver | ipa_dns_client | ensure dns entry is created
  freeipa.ansible_freeipa.ipadnsrecord:
    ipaadmin_password: "{{ company_realm_password }}"
    zone_name: "{{ company_domain }}"
    name: "{{ (hostname | default(nameserver_machine_hostname.stdout)) | replace('.' + company_domain, '') }}"
    a_rec: "{{ current_host_ip.msg }}"
    create_reverse: yes
    state: present
  no_log: "{{ secure_logs }}"
  delegate_to: "{{ groups[idm_group][0] }}" # TODO concat all masters IPs
