---
- name: ansible-nameserver | manage_zones | create serial timestamp
  command: "date +%y%m%d%H" # a mix behind idempotence and acceptable human pause
  register: bind_timestamp
  changed_when: false

- name: ansible-nameserver | manage_zones | configuring bind zones
  template:
    src: etc/bind/named.conf.local.j2
    dest: "{{ bind_conf_dir }}/named.conf.local"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - ansible-nameserver | reload bind

- name: ansible-nameserver | manage_zones | ensuring {{ bind_zones_dir }} exists
  file:
    path: "{{ bind_zones_dir }}"
    state: directory
    mode: 0755
  become: true
  when: inventory_hostname in groups[bind_masters]

- name: ansible-nameserver | manage_zones | creating forward zones
  template:
    src: etc/bind/zones/forward_zone.j2
    dest: "{{ bind_zones_dir + '/db.' + item['zone'] }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - ansible-nameserver | reload bind
  with_items: "{{ bind_forward_zones }}"
  when: inventory_hostname in groups[bind_masters]

- name: ansible-nameserver | manage_zones | creating reverse zones
  template:
    src: etc/bind/zones/reverse_zone.j2
    dest: "{{ bind_zones_dir + '/db.' + item['zone'] }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - ansible-nameserver | reload bind
  with_items: "{{ bind_reverse_zones }}"
  when: inventory_hostname in groups[bind_masters]
