---
- name: ansible-nameserver | prereq | install netaddr
  ansible.builtin.package:
    name: python-netaddr
    state: present
  become: True

- name: ansible-nameserver | prereq | get current hostname
  command: "hostname"
  register: nameserver_machine_hostname
  changed_when: false

- name: ansible-nameserver | deps | compute hostname
  ansible.builtin.debug:
    msg: "{{ hostname | default(nameserver_machine_hostname.stdout) }}"
  register: nameserver_computed_host

- name: ansible-nameserver | prereq | retreive current machine ip
  setup:
  register: current_host_facts
  delegate_facts: true

- name: ansible-nameserver | prereq | compute ip if preferred_nic is not set
  ansible.builtin.debug:
    msg: "{{ current_host_facts.ansible_facts['ansible_' + preferred_nic].ipv4.address if preferred_nic is defined else current_host_facts.ansible_facts.ansible_default_ipv4.address | default(current_host_facts.ansible_facts.ansible_all_ipv4_addresses[0]) }}"
  register: current_host_ip
