---
- name: ansible-nameserver | deps | set hostname
  ansible.builtin.include_role:
    name: tcharl.ansible_hostname
  vars:
    hostname: "{{ nameserver_computed_host.msg }}"
    hostname_reboot: false
    ansible_become: true
  tags:
    - dependency
