---
- name: Requirements | set hostname
  ansible.builtin.include_role:
    name: tcharl.freeipa_server
  vars:
    standalone_role: True
    company_domain: "{{ company_domain }}" # That server's hostname will be should ipa."{{ company_domain }}"
    company_realm_password: "{{ company_realm_password }}"
    company_ad_password: "{{ company_ad_password }}"
  tags:
    - dependency
