---
- name: Converge
  hosts: all
  vars:
    standalone_role: False
    company_domain: osgiliath.test
    secure_logs: False
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
  roles:
    - role: tcharl.ansible_nameserver
