---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox

lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: Fedora-Molecule-Nameserver
    box: tcharl/fedora-31-cgroupv1
    memory: 4000
    cpus: 2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    groups:
      - bindmasters
      - bindclient
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
