---
dependency:
  name: galaxy
  options:
    requirements-file: requirements-collections.yml
    collections-path: ../community-collections
    role-file: requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox

lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: dns.osgiliath.test
    box: tcharl/fedora-33-cgroupv1
    provider_options:
      cpus: 2
      memory: 4096
    instance_raw_config_args:
      - "cache.enable :dnf"
      - "cache.auto_detect = false"
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE Controller', '--hostiocache', 'on']"
    groups:
      - bindmasters
      - bindclients
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
