---
- name: Converge
  hosts: all
  vars:
    standalone_role: False
    secure_logs: False
    preferred_nic: "eth1"
    company_domain: osgiliath.test
    idm_preferred_nic: "eth1"
  roles:
    - role: tcharl.ansible_nameserver
